// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: replacement.proto

package vision

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RobotReplacement struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Position   *Robot `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	Yellowteam bool   `protobuf:"varint,5,opt,name=yellowteam,proto3" json:"yellowteam,omitempty"`
	Turnon     bool   `protobuf:"varint,6,opt,name=turnon,proto3" json:"turnon,omitempty"`
}

func (x *RobotReplacement) Reset() {
	*x = RobotReplacement{}
	if protoimpl.UnsafeEnabled {
		mi := &file_replacement_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RobotReplacement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RobotReplacement) ProtoMessage() {}

func (x *RobotReplacement) ProtoReflect() protoreflect.Message {
	mi := &file_replacement_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RobotReplacement.ProtoReflect.Descriptor instead.
func (*RobotReplacement) Descriptor() ([]byte, []int) {
	return file_replacement_proto_rawDescGZIP(), []int{0}
}

func (x *RobotReplacement) GetPosition() *Robot {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *RobotReplacement) GetYellowteam() bool {
	if x != nil {
		return x.Yellowteam
	}
	return false
}

func (x *RobotReplacement) GetTurnon() bool {
	if x != nil {
		return x.Turnon
	}
	return false
}

type BallReplacement struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X  float64 `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y  float64 `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	Vx float64 `protobuf:"fixed64,3,opt,name=vx,proto3" json:"vx,omitempty"`
	Vy float64 `protobuf:"fixed64,4,opt,name=vy,proto3" json:"vy,omitempty"`
}

func (x *BallReplacement) Reset() {
	*x = BallReplacement{}
	if protoimpl.UnsafeEnabled {
		mi := &file_replacement_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BallReplacement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BallReplacement) ProtoMessage() {}

func (x *BallReplacement) ProtoReflect() protoreflect.Message {
	mi := &file_replacement_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BallReplacement.ProtoReflect.Descriptor instead.
func (*BallReplacement) Descriptor() ([]byte, []int) {
	return file_replacement_proto_rawDescGZIP(), []int{1}
}

func (x *BallReplacement) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *BallReplacement) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *BallReplacement) GetVx() float64 {
	if x != nil {
		return x.Vx
	}
	return 0
}

func (x *BallReplacement) GetVy() float64 {
	if x != nil {
		return x.Vy
	}
	return 0
}

type Replacement struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ball   *BallReplacement    `protobuf:"bytes,1,opt,name=ball,proto3" json:"ball,omitempty"`
	Robots []*RobotReplacement `protobuf:"bytes,2,rep,name=robots,proto3" json:"robots,omitempty"`
}

func (x *Replacement) Reset() {
	*x = Replacement{}
	if protoimpl.UnsafeEnabled {
		mi := &file_replacement_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Replacement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Replacement) ProtoMessage() {}

func (x *Replacement) ProtoReflect() protoreflect.Message {
	mi := &file_replacement_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Replacement.ProtoReflect.Descriptor instead.
func (*Replacement) Descriptor() ([]byte, []int) {
	return file_replacement_proto_rawDescGZIP(), []int{2}
}

func (x *Replacement) GetBall() *BallReplacement {
	if x != nil {
		return x.Ball
	}
	return nil
}

func (x *Replacement) GetRobots() []*RobotReplacement {
	if x != nil {
		return x.Robots
	}
	return nil
}

var File_replacement_proto protoreflect.FileDescriptor

var file_replacement_proto_rawDesc = []byte{
	0x0a, 0x11, 0x72, 0x65, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x17, 0x66, 0x69, 0x72, 0x61, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x2e, 0x73, 0x69, 0x6d, 0x5f, 0x74, 0x6f, 0x5f, 0x72, 0x65, 0x66, 0x1a, 0x0c, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7b, 0x0a, 0x10, 0x52, 0x6f,
	0x62, 0x6f, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x2f,
	0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x13, 0x2e, 0x66, 0x69, 0x72, 0x61, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e,
	0x52, 0x6f, 0x62, 0x6f, 0x74, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x1e, 0x0a, 0x0a, 0x79, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x74, 0x65, 0x61, 0x6d, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x0a, 0x79, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x74, 0x65, 0x61, 0x6d, 0x12,
	0x16, 0x0a, 0x06, 0x74, 0x75, 0x72, 0x6e, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x06, 0x74, 0x75, 0x72, 0x6e, 0x6f, 0x6e, 0x22, 0x4d, 0x0a, 0x0f, 0x42, 0x61, 0x6c, 0x6c, 0x52,
	0x65, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x01, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x76, 0x78, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x02, 0x76, 0x78, 0x12, 0x0e, 0x0a, 0x02, 0x76, 0x79, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x02, 0x76, 0x79, 0x22, 0x8e, 0x01, 0x0a, 0x0b, 0x52, 0x65, 0x70, 0x6c, 0x61,
	0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x3c, 0x0a, 0x04, 0x62, 0x61, 0x6c, 0x6c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x66, 0x69, 0x72, 0x61, 0x5f, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x2e, 0x73, 0x69, 0x6d, 0x5f, 0x74, 0x6f, 0x5f, 0x72, 0x65, 0x66, 0x2e, 0x42,
	0x61, 0x6c, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x04,
	0x62, 0x61, 0x6c, 0x6c, 0x12, 0x41, 0x0a, 0x06, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x66, 0x69, 0x72, 0x61, 0x5f, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x2e, 0x73, 0x69, 0x6d, 0x5f, 0x74, 0x6f, 0x5f, 0x72, 0x65, 0x66, 0x2e, 0x52,
	0x6f, 0x62, 0x6f, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52,
	0x06, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x73, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x56, 0x53, 0x53, 0x53, 0x4c, 0x65, 0x61, 0x67, 0x75, 0x65,
	0x2f, 0x76, 0x73, 0x73, 0x73, 0x2d, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x2d, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_replacement_proto_rawDescOnce sync.Once
	file_replacement_proto_rawDescData = file_replacement_proto_rawDesc
)

func file_replacement_proto_rawDescGZIP() []byte {
	file_replacement_proto_rawDescOnce.Do(func() {
		file_replacement_proto_rawDescData = protoimpl.X.CompressGZIP(file_replacement_proto_rawDescData)
	})
	return file_replacement_proto_rawDescData
}

var file_replacement_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_replacement_proto_goTypes = []interface{}{
	(*RobotReplacement)(nil), // 0: fira_message.sim_to_ref.RobotReplacement
	(*BallReplacement)(nil),  // 1: fira_message.sim_to_ref.BallReplacement
	(*Replacement)(nil),      // 2: fira_message.sim_to_ref.Replacement
	(*Robot)(nil),            // 3: fira_message.Robot
}
var file_replacement_proto_depIdxs = []int32{
	3, // 0: fira_message.sim_to_ref.RobotReplacement.position:type_name -> fira_message.Robot
	1, // 1: fira_message.sim_to_ref.Replacement.ball:type_name -> fira_message.sim_to_ref.BallReplacement
	0, // 2: fira_message.sim_to_ref.Replacement.robots:type_name -> fira_message.sim_to_ref.RobotReplacement
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_replacement_proto_init() }
func file_replacement_proto_init() {
	if File_replacement_proto != nil {
		return
	}
	file_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_replacement_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RobotReplacement); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_replacement_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BallReplacement); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_replacement_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Replacement); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_replacement_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_replacement_proto_goTypes,
		DependencyIndexes: file_replacement_proto_depIdxs,
		MessageInfos:      file_replacement_proto_msgTypes,
	}.Build()
	File_replacement_proto = out.File
	file_replacement_proto_rawDesc = nil
	file_replacement_proto_goTypes = nil
	file_replacement_proto_depIdxs = nil
}
